### ISSUE TITLE
where is the library  file <pronet1.p4>

### ISSUE THREAD

**Issue by l-x007** [jiarong0907/Ripple#1]
When I compiled the output file, I couldn't find the library file < pronet1 P4 >, where can I find this library file

**Comment by jiarong0907** [comment]
Hi, this is because the code is generated for ns3 that is slightly different from bmv2. A quick fix is to replace the header file and ipv4 protocol constant as the following:

```
#include <core.p4>
#include <v1model.p4>
const bit<16> TYPE_IPV4 = 0x0800;
```

Note that you also need to change the header stack and parser, deparser to make it run on bmv2. The current L2 header is ppp not ethernet, but you can just replace it with a regular ethernet.

I will update the code over the weekend.

**Comment by l-x007** [comment]
Thank you for your reply! I will try to modify the code. At the same time, I am looking forward to the update of the code.

**Comment by jiarong0907** [comment]
Hi, the code has been fixed. Have fun with the code!

**Comment by l-x007** [comment]
Thank you for fixing the code! I will study the code carefully and wish you a happy life！

**Comment by jiarong0907** [comment]
Sure, you could email `xingjiarong0907@gmail.com`

**Comment by flash6666** [comment]
thank you . Sorry, I want to contact l-x007

**Comment by jiarong0907** [comment]
Sounds good. Please go ahead. -:)

**Comment by l-x007** [comment]
> thank you . Sorry, I want to contact l-x007

I'm sorry I just saw that you want to contact me,you could email linlixue901@163.com
